project:
  type: website

website:
  title: "ISSS609-AY2023-24T4"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Assignments
        menu:
        - assignment_1.qmd
        - assignment_2.qmd 
        - assignment_3.qmd
      - text: In class exercises
        menu:
        - in-class/In-class_Ex01.qmd
        - in-class/In-class_Ex02.qmd
        - in-class/In-class_Ex03.qmd
        - in-class/In-class_Ex04.qmd
        - in-class/In-class_Ex05.qmd
        - in-class/In-class_Ex06.qmd
        - in-class/In-class_Ex07.qmd
        - in-class/In-class_Ex09.qmd      
      - text: Hands-on exercises
        menu:
        - hands-on/hands_on_1.qmd
        - hands-on/hands_on_2.qmd
        - hands-on/hands_on_3.qmd
        - hands-on/hands_on_4.qmd
        - hands-on/hands_on_5.qmd
        - hands-on/hands_on_6.qmd
        - hands-on/hands_on_7.qmd
        - hands-on/hands_on_8.qmd
        - hands-on/hands_on_9.qmd
        - hands-on/hands_on_10.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

