project:
  type: website

website:
  title: "ISSS609-AY2023-24T4"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: assignment_1.qmd
        text: Assgnment 1

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

