project:
  type: website

website:
  title: "ISSS609-AY2023-24T4"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Assignments
        menu:
        - assignment_1.qmd
        - assignment_2.qmd 
        - assignment_3.qmd
      - text: In class exercises
        menu:
        - in-class/In-class_Ex03.qmd
        - in-class/In-class_Ex09.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

