```{r}
pacman::p_load(tidyverse, ggstatsplot)
exam <- read_csv("data/Exam_data.csv")
```

```{r}
set.seed(1234)
gghistostats(data=exam, 
             x=ENGLISH, 
             type="parametric", 
             test.value=60, 
             bin.args=list(color = "black", 
                           fill = "grey50", 
                           alpha=0.7), 
             normal.curve = FALSE, 
             normal.curve.args = list(linewidth=2), 
             xlab="English scores")
```

```{r}

set.seed(1234)
gghistostats(data=exam, 
             x=ENGLISH, 
             type="np", 
             test.value=60, 
             bin.args=list(color = "black", 
                           fill = "grey50", 
                           alpha=0.7), 
             normal.curve = FALSE, 
             normal.curve.args = list(linewidth=2), 
             xlab="English scores")
```


```{r}

exam_long = exam %>%
  pivot_longer(
    cols = ENGLISH:SCIENCE,
    names_to = "SUBJECT",
    values_to = "SCORES") %>%
  filter(CLASS == "3A")

head(exam_long)
```

```{r}
ggwithinstats(
  data= filter(exam_long, 
               SUBJECT %in% 
                 c("MATHS", "SCIENCE")),
  x = SUBJECT,
  y = SCORES,
  type = "p"
)
```

```{r}
ggscatterstats(
  data = exam,
  x = MATHS,
  y = ENGLISH,
  marginal = TRUE,
  label.var = ID,
  label.expression = ENGLISH > 90 & MATHS > 90
)
```
